# Data Structure

<h2>Soal 1: Perbedaan Data Structure</h2>

Jawab Pertanyaan di bawah ini:

Jelaskan perbedaan dari List, Tuple, Set dan Dictionary!

List, Tuple, Set, dan Dictionary adalah empat jenis struktur data di Python yang memiliki karakteristik berbeda sesuai dengan kebutuhan penggunaannya.


*   List adalah struktur data yang paling fleksibel,memungkinkan kita mengakses elemen menggunakan indeks secara berurutan (sequential) dan memanipulasi elemen karena sifatnya yang mutable. List juga mendukung elemen yang duplikat dan bersifat iterable sehingga cocok untuk menyimpan data dalam urutan tertentu.
*   Tuple, di sisi lain, memiliki sifat yang lebih kaku karena bersifat immutable, artinya elemen di dalamnya tidak dapat diubah setelah tuple dibuat. Namun, seperti List, Tuple juga mendukung pengaksesan elemen secara berurutan dan dapat menyimpan elemen yang duplikat. Tuple sering digunakan ketika data tidak boleh diubah.
*   Berbeda dengan List dan Tuple, Set adalah struktur data yang hanya menyimpan elemen-elemen unik, sehingga tidak mengizinkan adanya elemen yang duplikat. Set tidak mendukung pengaksesan elemen berdasarkan indeks karena bersifat non-sequential, tetapi bersifat mutable, memungkinkan elemen untuk ditambah atau dihapus. Set memiliki karakteristik seperti himpunan dalam matematika, misalnya mendukung operasi seperti union, intersection, dan difference, tetapi elemen-elemen dalam Set tidak dijamin berurutan.
*   Sementara itu, Dictionary adalah struktur data yang menyimpan pasangan key-value. Tidak seperti List, Tuple, dan Set yang hanya menyimpan elemen tunggal, Dictionary mengasosiasikan setiap elemen (value) dengan sebuah kunci unik (key). Key dalam Dictionary harus bersifat immutable (seperti string, angka, atau tuple), tetapi value bisa berupa tipe data apa pun, termasuk struktur data lainnya. Dictionary bersifat mutable, sehingga pasangan key-value dapat ditambah, dihapus, atau diubah. Elemen dalam Dictionary tidak berurutan (non-sequential), tetapi dapat diakses secara langsung menggunakan key, bukan indeks. Dictionary sangat berguna untuk menyimpan data yang memiliki hubungan atau asosiasi, seperti data berbentuk tabel.


Perbedaan utama di antara keempatnya terletak pada struktur penyimpanan, cara pengaksesan elemen (indeks vs key), sifat mutable/immutable, dan dukungan elemen duplikat. List dan Tuple cocok untuk data yang berurutan, Set untuk data unik tanpa urutan, sedangkan Dictionary ideal untuk data dengan hubungan key-value.



---



---



# List

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [17]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list

slice_list= a[1:5]
print(slice_list)

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
subset = a[1][::2]
print(subset)

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 4: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [3]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2]=10
a[1][0]=11

print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 5: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [20]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del areas[8:10]

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 6: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [23]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T =[i for i in S if i % 2==0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]



---



---



# Tuple

## Soal 7. Mengakses Tuple

Gunakan cara sclicing untuk mengakses tuple sehingga mendapatkan hasil sesuai expected output

In [25]:
tuple_1 = (1, 2, 6, 7, 8, 9, 10)

#akses tuple
print(tuple_1[2:5])

(6, 7, 8)


Expected Outpout:


(6, 7, 8)



---



---



# Dictionary

<h2>Soal 8: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [31]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe['itali']='roma'

# cek apakah itali ada di dalam objek dictionary
is_check = 'itali' in europe
print(is_check)

True


Expected Output:
    
True

<h2>Soal 9: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [33]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe['germany']='berlin'

# remove australia dari europa
europe.pop('australia')

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 10: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [49]:
country = {
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 }
         }

# berapa populasi dari kota german?
populasi=country['germany']['population']
print(populasi)
# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country['indonesia']={ 'capital':'jakarta', 'population':250 }

print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 11: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [56]:
country = {
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for country_name, details in country.items():
    print('Ibukota '+country_name+' adalah ' + details['capital'])

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta



---



---



# Set

## Soal 12: Remove Duplicate using set


Hilangkan nilai duplikat dari sebuah objek list dengan menggunakan cara set sehingga menjadi sebuah tipe set

In [58]:
obj_list = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 9, 10]

#using set
duplikat = set(obj_list)

print(duplikat)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


Expected output:

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## Soal 13: Mengubah dan menghapus anggota set

Ubahlah dan hapus anggota set sehingga mendapatkan hasil yang diinginkan


In [13]:
set_1 = {1, 2, 3, 4, 5}

#tambahkan anggota set dengan nilai {6,7,8}
set_5 = {6,7,8}
union=set_1 | set_5

#hapus nilai anggota set 8
union.remove(8)
print(union)

{1, 2, 3, 4, 5, 6, 7}


Expected output:

{1, 2, 3, 4, 5, 6, 7}

## Soal 14: Operasi pada Set

Carilah irisan dari ke dua set dengan menggunakan metode intersection

In [6]:
set_2 = {6, 8, 9, 10, 24}
set_3 = {6, 10, 8, 25, 13}

#intersection set
inter_result=set_2 & set_3
sorted_inter=sorted(inter_result)
print(sorted_inter)

[6, 8, 10]


Expected output:


{6, 8, 10}



---



---

